### ISSUE TITLE
Port RPi / armhf Dockerfile for latest AlertManager RC

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#582]
We need AlertManager to be ported over to the contrib folder where we have ARM build files for Prometheus 2.0 / 2.2 etc already in place.

Please use this as a basis for the build:

https://github.com/alexellis/docker-arm/tree/master/images/armhf/alertmanager

If you have access to a Raspberry Pi that will help a lot otherwise provision a node on Scaleway for a couple of hours to test your build.

## Task

* [ ] Port Dockerfile to latest AlertManager as per https://github.com/openfaas/faas/blob/master/docker-compose.yml#L134
* [ ] Build and test that alert manager functions
* [ ] Ping me to build/push a new manual ARM image via the project account

**Comment by rgee0** [comment]
I'll have a look at this.

I'll add the label to the network as part of this too.

**Comment by alexellis** [comment]
I appreciate it. Our Kubernetes config is broken right now on ARM. Do you have an ETA?
