### ISSUE TITLE
Support additional HTTP verbs

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#815]
## Feature

It appears that more and more users are looking to OpenFaaS for stateless microservices as well as functions, they expect a set of "REST"-like features including expansion of HTTP verbs and additional path support i.e. #789

This feature adds support for additional HTTP verbs: DELETE, PUT, PATCH. 

## Design considerations

GET and POST are currently supported by the gateway, so the mux/router needs to expand to allow multiple verbs or all verbs and then validate at that point.

To implement these changes a full vertical slice will be needed covering every layer:

- gateway

This includes Prometheus metrics and the certifier tests

- provider (for non direct-functions use-cases, i.e. faas-fargate)

All providers need to be updated and validated. faas-swarm, faas-netes, faas-operator

- watchdog (and of-watchdog)

Including new unit tests where this is not supported.

- all official templates (and of-watchdog templates)

## Testing

In terms of testing it should be possible to invoke the function via `curl -X METHOD` and have this appear as an Http_Method environmental variable for the classic watchdog and for of-watchdog, this new value needs to be handled in the template and to be surfaced through the API request object in some way.

**Comment by alexellis** [comment]
of-watchdog -> https://github.com/openfaas-incubator/of-watchdog

**Comment by ewilde** [comment]
@alexellis do you want to have a way to invoke the new HTTP verbs in the UI? (I see the --method alread exists in the CLI)

**Comment by alexellis** [comment]
For now the UI could remain the same, leaving it to POST only.

**Comment by alexellis** [comment]
> provider (for non direct-functions use-cases, i.e. faas-fargate)
> All providers need to be updated and validated. faas-swarm, faas-netes, faas-operator

Example of where direct-functions is disabled and the functions are called via the back-end:

https://github.com/openfaas/faas-swarm/blob/master/handlers/proxy.go#L49

I know that CapitalOne needed to use this in their locked-down Kubernetes environment with faas-netes.

**Comment by alexellis** [comment]
Additional verbs to be added for /function and /async-function endpoints (only):

> This feature adds support for additional HTTP verbs: DELETE, PUT, PATCH.

There are other verbs which are often used with REST, but these are not part of the initial PR which should be incremental.

**Comment by alexellis** [comment]
@ewilde can this be closed yet? (feel free to use `Derek close` with any issues/PRs)

**Comment by ewilde** [comment]
@alexellis still some items to investigate & complete

# Tasks
- [x] [Cli support for PUT, PATCH, DELETE](https://github.com/openfaas/faas-cli/pull/505)
- [x] [Watchdog add PATCH](https://github.com/openfaas/faas/pull/822)
- [x] [Certifier tests for new verbs](https://github.com/openfaas/certifier/pull/10)
- [x] [Update alpine function to use version 0.9> of watchdog with patch support](https://github.com/openfaas/faas/pull/840)
- [x] [proxy function support in docker swarm](https://github.com/openfaas/faas-swarm/commit/85782ed1330ed931d794049f45ae75682b53356a)
- [x] [proxy function support in faas-netes](https://github.com/openfaas/faas-netes/commit/3b2e0d5ef9f56e6b87d2b5566bb4102c399c156a)
- [x] [proxy function support in faas-operator](https://github.com/openfaas-incubator/openfaas-operator/commit/5548b019fe49b2f7f7d31f354f6825c2546ed751)
- [ ] Official language templates to use version 0.9> of watchdog
- [ ] `of-watchdog` see if anything needs the verbs here
- [ ]  Prometheus metrics, not sure what needs doing here, but mentioned in the issue text

**Comment by alexellis** [comment]
@ewilde can we close or do we need to do more work?

**Comment by ewilde** [comment]
@alexellis will check and reply on this thread

**Comment by alexellis** [comment]
@ewilde ping / bump ^
